function [] = CheckNormalization
% No inputs required. No physical outputs are given in the workspace. The
% only outputs will be the check registration images generated by SPM.
%
% Function that allows user to interactively choose which subject to
% perform SPM's Check Normalization function. This functional specifically
% is made for users to check if the normalized mean function, normalized T1, and
% T1.nii template were correctly registered to each other. To perform this
% visual check, click around and make sure the corners of the ventricles
% are aligned.
%
% Script written by Khoi - June 31, 2013
% Requires SPM toolbox.

%mainDir = uigetdir(pwd,'Choose source directory for all preprocessed data');
mainDir = uigetdir(pwd,'Choose Preprocessed Directory');

try
    dstore = get_any_files('.DS_Store',mainDir);
    for i = 1:length(dstore)
        delete(dstore{i});
    end
catch
end

%Get list of all folders containing dicoms (one per subject)
batchList = strsplit(sprintf('%s',strtrim(ls(mainDir))));

selection = listdlg('PromptString','Select a subject',...
    'SelectionMode','single',...
    'ListString',batchList);

sourcename = fullfile(mainDir,batchList{selection});

meanFunc = get_any_files('wmeana',sourcename); %will get all means - use 1st image
regT1 = get_any_files('wr',fullfile(sourcename,'t1')); %will get all registered T1 - use 4th image

checkRegImg = [spm_vol(meanFunc{2});spm_vol(regT1{2});spm_vol(which('T1.nii'))];
captions = {'Normalized Mean Functional';'Normalized Registered T1';'T1 Template'};


spm_check_registration(checkRegImg,captions);


% check normalization on segmentation?


